package main

const (
	LDR_PACKET_DIR_READ = 0
	LDR_PACKET_DIR_WRITE = 1
	LDR_PACKET_REP_WRITE = 2
	LDR_PACKET_REP_SECURE = 3
	LDR_PACKET_REP_READ = 4
	LDR_PACKET_REP_GOSSIP = 5
	LDR_PACKET_RESPONSE = 6
)
